FROM node:22 AS frontend-build

WORKDIR /app

COPY frontend .

RUN npm install

RUN npm run build

FROM nginx:latest

COPY nginx/prod-default.conf /etc/nginx/conf.d/default.conf

COPY --from=frontend-build /app/dist /usr/share/nginx/html

COPY backend /var/www/html